version: '3'
services:
  osint_client_nginx:
    image: osint_frontend:latest
    container_name: osint_client_nginx
    volumes:
      - ./nginx/extend:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - osint_client_backend
    networks:
      - osint_client-network

  osint_client_backend:
    image: osint_backend:latest
    container_name: osint_client_backend
    build: ./
    environment:
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=${POSTGRES_USER}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=osint_client_db
    networks:
      - osint_client-network
    depends_on:
      - osint_client_db
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --root-path /api --port 8000 --workers 6

  osint_client_db:
    image: postgres:15
    container_name: osint_client_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - osint_client-network
    volumes:
      - ../osint_client_db:/var/lib/postgresql/data

networks:
  osint_client-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 18.98.5.0/24
