version: '3'
services:
  osint_client_nginx:
    image: nginx:latest
    container_name: osint_client_nginx
    volumes:
      - ./nginx/extend:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - osint_client_backend
    networks:
      - osint_client-network

  osint_client_backend:
    image: osint_client:latest
    container_name: osint_client_backend
    build: ./
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PASSWORD=osint_client
      - DB_USER=osint_client
      - DB_NAME=osint_client
      - DB_HOST=osint_client_db
      - TG_API_ID=24285166
      - TG_API_HASH=20f7fa4cd6ba12ba52c49629af3b5c3f
      - TG_PHONE=+38268381500
      # - TG_API_ID=25223960
      # - TG_API_HASH=1cbc549f14385c725205c1e48a5264bc
      # - TG_PHONE=+380632033140
      # - TELETHON_SESSION=real_acc.session
      - USE_TELETHON=1
      - REDIS_URI=osint_client_redis
      - ALEPH_API_TOKEN=08611ccde27f4e83ac850a7b7f3527b7
      - DEBUG=1
    networks:
      - osint_client-network
    depends_on:
      - osint_client_db
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --root-path /api --port 8000 --reload

  osint_client_backend_websocket:
    image: osint_client:latest
    container_name: osint_client_backend_websocket
    build: ./
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PASSWORD=osint_client
      - DB_USER=osint_client
      - DB_NAME=osint_client
      - DB_HOST=osint_client_db
      - TG_API_ID=24285166
      - TG_API_HASH=20f7fa4cd6ba12ba52c49629af3b5c3f
      - TG_PHONE=+38268381500
      # - TG_API_ID=25223960
      # - TG_API_HASH=1cbc549f14385c725205c1e48a5264bc
      # - TG_PHONE=+380632033140
      # - TELETHON_SESSION=real_acc.session
      - USE_TELETHON=1
      - REDIS_URI=osint_client_redis
      - ALEPH_API_TOKEN=08611ccde27f4e83ac850a7b7f3527b7
      - DEBUG=1
    networks:
      - osint_client-network
    depends_on:
      - osint_client_db
    ports:
      - 5678:5678
    volumes:
      - ./:/app
    command: sh -c 'cd websocket; uvicorn main:app --host 0.0.0.0 --port 5678'

  osint_client_db:
    image: postgres:15
    container_name: osint_client_db
    environment:
      - POSTGRES_PASSWORD=osint_client
      - POSTGRES_USER=osint_client
      - POSTGRES_DB=osint_client
    networks:
      - osint_client-network
    # ports:
    #   - 5432:5432
    volumes:
      - ../osint_client_db:/var/lib/postgresql/data

  osint_client_redis:
    image: redis:latest
    container_name: osint_client_redis
    networks:
      - osint_client-network

networks:
  osint_client-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 18.98.5.0/24
