"""add_accessed_role_provider

Revision ID: dae6f09f609a
Revises: 730585332c4e
Create Date: 2024-05-31 20:35:14.403397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae6f09f609a'
down_revision = '730585332c4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('accessed_role', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'accessed_role')
    # ### end Alembic commands ###
